/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockIndexRouteImport } from './routes/stock/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as QuantityUnitsIndexRouteImport } from './routes/quantity-units/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as RecipesIdRouteImport } from './routes/recipes/$id'
import { Route as QuantityUnitsIdRouteImport } from './routes/quantity-units/$id'
import { Route as ProductsIdRouteImport } from './routes/products/$id'
import { Route as CategoriesIdRouteImport } from './routes/categories/$id'
import { Route as ApiUploadsIndexRouteImport } from './routes/api/uploads/index'
import { Route as ApiUnitConversionsIndexRouteImport } from './routes/api/unit-conversions/index'
import { Route as ApiStockLogsIndexRouteImport } from './routes/api/stock-logs/index'
import { Route as ApiStockEntriesIndexRouteImport } from './routes/api/stock-entries/index'
import { Route as ApiRecipesIndexRouteImport } from './routes/api/recipes/index'
import { Route as ApiQuantityUnitsIndexRouteImport } from './routes/api/quantity-units/index'
import { Route as ApiProductsIndexRouteImport } from './routes/api/products/index'
import { Route as ApiCategoriesIndexRouteImport } from './routes/api/categories/index'
import { Route as ApiUploadsFilenameRouteImport } from './routes/api/uploads/$filename'
import { Route as ApiUnitConversionsIdRouteImport } from './routes/api/unit-conversions/$id'
import { Route as ApiStockLogsIdRouteImport } from './routes/api/stock-logs/$id'
import { Route as ApiStockEntriesConsumeRouteImport } from './routes/api/stock-entries/consume'
import { Route as ApiStockEntriesIdRouteImport } from './routes/api/stock-entries/$id'
import { Route as ApiRecipesIdRouteImport } from './routes/api/recipes/$id'
import { Route as ApiQuantityUnitsIdRouteImport } from './routes/api/quantity-units/$id'
import { Route as ApiProductsIdRouteImport } from './routes/api/products/$id'
import { Route as ApiCategoriesIdRouteImport } from './routes/api/categories/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRecipesIdIngredientsIndexRouteImport } from './routes/api/recipes/$id/ingredients/index'
import { Route as ApiRecipesIdIngredientsIngredientIdRouteImport } from './routes/api/recipes/$id/ingredients/$ingredientId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantityUnitsIndexRoute = QuantityUnitsIndexRouteImport.update({
  id: '/quantity-units/',
  path: '/quantity-units/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantityUnitsIdRoute = QuantityUnitsIdRouteImport.update({
  id: '/quantity-units/$id',
  path: '/quantity-units/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIdRoute = CategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsIndexRoute = ApiUploadsIndexRouteImport.update({
  id: '/api/uploads/',
  path: '/api/uploads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnitConversionsIndexRoute = ApiUnitConversionsIndexRouteImport.update({
  id: '/api/unit-conversions/',
  path: '/api/unit-conversions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStockLogsIndexRoute = ApiStockLogsIndexRouteImport.update({
  id: '/api/stock-logs/',
  path: '/api/stock-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStockEntriesIndexRoute = ApiStockEntriesIndexRouteImport.update({
  id: '/api/stock-entries/',
  path: '/api/stock-entries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesIndexRoute = ApiRecipesIndexRouteImport.update({
  id: '/api/recipes/',
  path: '/api/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuantityUnitsIndexRoute = ApiQuantityUnitsIndexRouteImport.update({
  id: '/api/quantity-units/',
  path: '/api/quantity-units/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIndexRoute = ApiProductsIndexRouteImport.update({
  id: '/api/products/',
  path: '/api/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesIndexRoute = ApiCategoriesIndexRouteImport.update({
  id: '/api/categories/',
  path: '/api/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsFilenameRoute = ApiUploadsFilenameRouteImport.update({
  id: '/api/uploads/$filename',
  path: '/api/uploads/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnitConversionsIdRoute = ApiUnitConversionsIdRouteImport.update({
  id: '/api/unit-conversions/$id',
  path: '/api/unit-conversions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStockLogsIdRoute = ApiStockLogsIdRouteImport.update({
  id: '/api/stock-logs/$id',
  path: '/api/stock-logs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStockEntriesConsumeRoute = ApiStockEntriesConsumeRouteImport.update({
  id: '/api/stock-entries/consume',
  path: '/api/stock-entries/consume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStockEntriesIdRoute = ApiStockEntriesIdRouteImport.update({
  id: '/api/stock-entries/$id',
  path: '/api/stock-entries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesIdRoute = ApiRecipesIdRouteImport.update({
  id: '/api/recipes/$id',
  path: '/api/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuantityUnitsIdRoute = ApiQuantityUnitsIdRouteImport.update({
  id: '/api/quantity-units/$id',
  path: '/api/quantity-units/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/api/products/$id',
  path: '/api/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesIdRoute = ApiCategoriesIdRouteImport.update({
  id: '/api/categories/$id',
  path: '/api/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesIdIngredientsIndexRoute =
  ApiRecipesIdIngredientsIndexRouteImport.update({
    id: '/ingredients/',
    path: '/ingredients/',
    getParentRoute: () => ApiRecipesIdRoute,
  } as any)
const ApiRecipesIdIngredientsIngredientIdRoute =
  ApiRecipesIdIngredientsIngredientIdRouteImport.update({
    id: '/ingredients/$ingredientId',
    path: '/ingredients/$ingredientId',
    getParentRoute: () => ApiRecipesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/quantity-units/$id': typeof QuantityUnitsIdRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/quantity-units/': typeof QuantityUnitsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/stock/': typeof StockIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/quantity-units/$id': typeof ApiQuantityUnitsIdRoute
  '/api/recipes/$id': typeof ApiRecipesIdRouteWithChildren
  '/api/stock-entries/$id': typeof ApiStockEntriesIdRoute
  '/api/stock-entries/consume': typeof ApiStockEntriesConsumeRoute
  '/api/stock-logs/$id': typeof ApiStockLogsIdRoute
  '/api/unit-conversions/$id': typeof ApiUnitConversionsIdRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/products/': typeof ApiProductsIndexRoute
  '/api/quantity-units/': typeof ApiQuantityUnitsIndexRoute
  '/api/recipes/': typeof ApiRecipesIndexRoute
  '/api/stock-entries/': typeof ApiStockEntriesIndexRoute
  '/api/stock-logs/': typeof ApiStockLogsIndexRoute
  '/api/unit-conversions/': typeof ApiUnitConversionsIndexRoute
  '/api/uploads/': typeof ApiUploadsIndexRoute
  '/api/recipes/$id/ingredients/$ingredientId': typeof ApiRecipesIdIngredientsIngredientIdRoute
  '/api/recipes/$id/ingredients/': typeof ApiRecipesIdIngredientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/quantity-units/$id': typeof QuantityUnitsIdRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/quantity-units': typeof QuantityUnitsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/stock': typeof StockIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/quantity-units/$id': typeof ApiQuantityUnitsIdRoute
  '/api/recipes/$id': typeof ApiRecipesIdRouteWithChildren
  '/api/stock-entries/$id': typeof ApiStockEntriesIdRoute
  '/api/stock-entries/consume': typeof ApiStockEntriesConsumeRoute
  '/api/stock-logs/$id': typeof ApiStockLogsIdRoute
  '/api/unit-conversions/$id': typeof ApiUnitConversionsIdRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/api/categories': typeof ApiCategoriesIndexRoute
  '/api/products': typeof ApiProductsIndexRoute
  '/api/quantity-units': typeof ApiQuantityUnitsIndexRoute
  '/api/recipes': typeof ApiRecipesIndexRoute
  '/api/stock-entries': typeof ApiStockEntriesIndexRoute
  '/api/stock-logs': typeof ApiStockLogsIndexRoute
  '/api/unit-conversions': typeof ApiUnitConversionsIndexRoute
  '/api/uploads': typeof ApiUploadsIndexRoute
  '/api/recipes/$id/ingredients/$ingredientId': typeof ApiRecipesIdIngredientsIngredientIdRoute
  '/api/recipes/$id/ingredients': typeof ApiRecipesIdIngredientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/quantity-units/$id': typeof QuantityUnitsIdRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/quantity-units/': typeof QuantityUnitsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/stock/': typeof StockIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/quantity-units/$id': typeof ApiQuantityUnitsIdRoute
  '/api/recipes/$id': typeof ApiRecipesIdRouteWithChildren
  '/api/stock-entries/$id': typeof ApiStockEntriesIdRoute
  '/api/stock-entries/consume': typeof ApiStockEntriesConsumeRoute
  '/api/stock-logs/$id': typeof ApiStockLogsIdRoute
  '/api/unit-conversions/$id': typeof ApiUnitConversionsIdRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/products/': typeof ApiProductsIndexRoute
  '/api/quantity-units/': typeof ApiQuantityUnitsIndexRoute
  '/api/recipes/': typeof ApiRecipesIndexRoute
  '/api/stock-entries/': typeof ApiStockEntriesIndexRoute
  '/api/stock-logs/': typeof ApiStockLogsIndexRoute
  '/api/unit-conversions/': typeof ApiUnitConversionsIndexRoute
  '/api/uploads/': typeof ApiUploadsIndexRoute
  '/api/recipes/$id/ingredients/$ingredientId': typeof ApiRecipesIdIngredientsIngredientIdRoute
  '/api/recipes/$id/ingredients/': typeof ApiRecipesIdIngredientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/categories/$id'
    | '/products/$id'
    | '/quantity-units/$id'
    | '/recipes/$id'
    | '/categories/'
    | '/products/'
    | '/quantity-units/'
    | '/recipes/'
    | '/stock/'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/products/$id'
    | '/api/quantity-units/$id'
    | '/api/recipes/$id'
    | '/api/stock-entries/$id'
    | '/api/stock-entries/consume'
    | '/api/stock-logs/$id'
    | '/api/unit-conversions/$id'
    | '/api/uploads/$filename'
    | '/api/categories/'
    | '/api/products/'
    | '/api/quantity-units/'
    | '/api/recipes/'
    | '/api/stock-entries/'
    | '/api/stock-logs/'
    | '/api/unit-conversions/'
    | '/api/uploads/'
    | '/api/recipes/$id/ingredients/$ingredientId'
    | '/api/recipes/$id/ingredients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/categories/$id'
    | '/products/$id'
    | '/quantity-units/$id'
    | '/recipes/$id'
    | '/categories'
    | '/products'
    | '/quantity-units'
    | '/recipes'
    | '/stock'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/products/$id'
    | '/api/quantity-units/$id'
    | '/api/recipes/$id'
    | '/api/stock-entries/$id'
    | '/api/stock-entries/consume'
    | '/api/stock-logs/$id'
    | '/api/unit-conversions/$id'
    | '/api/uploads/$filename'
    | '/api/categories'
    | '/api/products'
    | '/api/quantity-units'
    | '/api/recipes'
    | '/api/stock-entries'
    | '/api/stock-logs'
    | '/api/unit-conversions'
    | '/api/uploads'
    | '/api/recipes/$id/ingredients/$ingredientId'
    | '/api/recipes/$id/ingredients'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/categories/$id'
    | '/products/$id'
    | '/quantity-units/$id'
    | '/recipes/$id'
    | '/categories/'
    | '/products/'
    | '/quantity-units/'
    | '/recipes/'
    | '/stock/'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/products/$id'
    | '/api/quantity-units/$id'
    | '/api/recipes/$id'
    | '/api/stock-entries/$id'
    | '/api/stock-entries/consume'
    | '/api/stock-logs/$id'
    | '/api/unit-conversions/$id'
    | '/api/uploads/$filename'
    | '/api/categories/'
    | '/api/products/'
    | '/api/quantity-units/'
    | '/api/recipes/'
    | '/api/stock-entries/'
    | '/api/stock-logs/'
    | '/api/unit-conversions/'
    | '/api/uploads/'
    | '/api/recipes/$id/ingredients/$ingredientId'
    | '/api/recipes/$id/ingredients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  CategoriesIdRoute: typeof CategoriesIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  QuantityUnitsIdRoute: typeof QuantityUnitsIdRoute
  RecipesIdRoute: typeof RecipesIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  QuantityUnitsIndexRoute: typeof QuantityUnitsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  StockIndexRoute: typeof StockIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCategoriesIdRoute: typeof ApiCategoriesIdRoute
  ApiProductsIdRoute: typeof ApiProductsIdRoute
  ApiQuantityUnitsIdRoute: typeof ApiQuantityUnitsIdRoute
  ApiRecipesIdRoute: typeof ApiRecipesIdRouteWithChildren
  ApiStockEntriesIdRoute: typeof ApiStockEntriesIdRoute
  ApiStockEntriesConsumeRoute: typeof ApiStockEntriesConsumeRoute
  ApiStockLogsIdRoute: typeof ApiStockLogsIdRoute
  ApiUnitConversionsIdRoute: typeof ApiUnitConversionsIdRoute
  ApiUploadsFilenameRoute: typeof ApiUploadsFilenameRoute
  ApiCategoriesIndexRoute: typeof ApiCategoriesIndexRoute
  ApiProductsIndexRoute: typeof ApiProductsIndexRoute
  ApiQuantityUnitsIndexRoute: typeof ApiQuantityUnitsIndexRoute
  ApiRecipesIndexRoute: typeof ApiRecipesIndexRoute
  ApiStockEntriesIndexRoute: typeof ApiStockEntriesIndexRoute
  ApiStockLogsIndexRoute: typeof ApiStockLogsIndexRoute
  ApiUnitConversionsIndexRoute: typeof ApiUnitConversionsIndexRoute
  ApiUploadsIndexRoute: typeof ApiUploadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/': {
      id: '/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantity-units/': {
      id: '/quantity-units/'
      path: '/quantity-units'
      fullPath: '/quantity-units/'
      preLoaderRoute: typeof QuantityUnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantity-units/$id': {
      id: '/quantity-units/$id'
      path: '/quantity-units/$id'
      fullPath: '/quantity-units/$id'
      preLoaderRoute: typeof QuantityUnitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$id': {
      id: '/categories/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof CategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/': {
      id: '/api/uploads/'
      path: '/api/uploads'
      fullPath: '/api/uploads/'
      preLoaderRoute: typeof ApiUploadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unit-conversions/': {
      id: '/api/unit-conversions/'
      path: '/api/unit-conversions'
      fullPath: '/api/unit-conversions/'
      preLoaderRoute: typeof ApiUnitConversionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stock-logs/': {
      id: '/api/stock-logs/'
      path: '/api/stock-logs'
      fullPath: '/api/stock-logs/'
      preLoaderRoute: typeof ApiStockLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stock-entries/': {
      id: '/api/stock-entries/'
      path: '/api/stock-entries'
      fullPath: '/api/stock-entries/'
      preLoaderRoute: typeof ApiStockEntriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/': {
      id: '/api/recipes/'
      path: '/api/recipes'
      fullPath: '/api/recipes/'
      preLoaderRoute: typeof ApiRecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quantity-units/': {
      id: '/api/quantity-units/'
      path: '/api/quantity-units'
      fullPath: '/api/quantity-units/'
      preLoaderRoute: typeof ApiQuantityUnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/': {
      id: '/api/products/'
      path: '/api/products'
      fullPath: '/api/products/'
      preLoaderRoute: typeof ApiProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/': {
      id: '/api/categories/'
      path: '/api/categories'
      fullPath: '/api/categories/'
      preLoaderRoute: typeof ApiCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$filename': {
      id: '/api/uploads/$filename'
      path: '/api/uploads/$filename'
      fullPath: '/api/uploads/$filename'
      preLoaderRoute: typeof ApiUploadsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unit-conversions/$id': {
      id: '/api/unit-conversions/$id'
      path: '/api/unit-conversions/$id'
      fullPath: '/api/unit-conversions/$id'
      preLoaderRoute: typeof ApiUnitConversionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stock-logs/$id': {
      id: '/api/stock-logs/$id'
      path: '/api/stock-logs/$id'
      fullPath: '/api/stock-logs/$id'
      preLoaderRoute: typeof ApiStockLogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stock-entries/consume': {
      id: '/api/stock-entries/consume'
      path: '/api/stock-entries/consume'
      fullPath: '/api/stock-entries/consume'
      preLoaderRoute: typeof ApiStockEntriesConsumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stock-entries/$id': {
      id: '/api/stock-entries/$id'
      path: '/api/stock-entries/$id'
      fullPath: '/api/stock-entries/$id'
      preLoaderRoute: typeof ApiStockEntriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/$id': {
      id: '/api/recipes/$id'
      path: '/api/recipes/$id'
      fullPath: '/api/recipes/$id'
      preLoaderRoute: typeof ApiRecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quantity-units/$id': {
      id: '/api/quantity-units/$id'
      path: '/api/quantity-units/$id'
      fullPath: '/api/quantity-units/$id'
      preLoaderRoute: typeof ApiQuantityUnitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/api/products/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/$id': {
      id: '/api/categories/$id'
      path: '/api/categories/$id'
      fullPath: '/api/categories/$id'
      preLoaderRoute: typeof ApiCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/$id/ingredients/': {
      id: '/api/recipes/$id/ingredients/'
      path: '/ingredients'
      fullPath: '/api/recipes/$id/ingredients/'
      preLoaderRoute: typeof ApiRecipesIdIngredientsIndexRouteImport
      parentRoute: typeof ApiRecipesIdRoute
    }
    '/api/recipes/$id/ingredients/$ingredientId': {
      id: '/api/recipes/$id/ingredients/$ingredientId'
      path: '/ingredients/$ingredientId'
      fullPath: '/api/recipes/$id/ingredients/$ingredientId'
      preLoaderRoute: typeof ApiRecipesIdIngredientsIngredientIdRouteImport
      parentRoute: typeof ApiRecipesIdRoute
    }
  }
}

interface ApiRecipesIdRouteChildren {
  ApiRecipesIdIngredientsIngredientIdRoute: typeof ApiRecipesIdIngredientsIngredientIdRoute
  ApiRecipesIdIngredientsIndexRoute: typeof ApiRecipesIdIngredientsIndexRoute
}

const ApiRecipesIdRouteChildren: ApiRecipesIdRouteChildren = {
  ApiRecipesIdIngredientsIngredientIdRoute:
    ApiRecipesIdIngredientsIngredientIdRoute,
  ApiRecipesIdIngredientsIndexRoute: ApiRecipesIdIngredientsIndexRoute,
}

const ApiRecipesIdRouteWithChildren = ApiRecipesIdRoute._addFileChildren(
  ApiRecipesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  CategoriesIdRoute: CategoriesIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  QuantityUnitsIdRoute: QuantityUnitsIdRoute,
  RecipesIdRoute: RecipesIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  QuantityUnitsIndexRoute: QuantityUnitsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  StockIndexRoute: StockIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCategoriesIdRoute: ApiCategoriesIdRoute,
  ApiProductsIdRoute: ApiProductsIdRoute,
  ApiQuantityUnitsIdRoute: ApiQuantityUnitsIdRoute,
  ApiRecipesIdRoute: ApiRecipesIdRouteWithChildren,
  ApiStockEntriesIdRoute: ApiStockEntriesIdRoute,
  ApiStockEntriesConsumeRoute: ApiStockEntriesConsumeRoute,
  ApiStockLogsIdRoute: ApiStockLogsIdRoute,
  ApiUnitConversionsIdRoute: ApiUnitConversionsIdRoute,
  ApiUploadsFilenameRoute: ApiUploadsFilenameRoute,
  ApiCategoriesIndexRoute: ApiCategoriesIndexRoute,
  ApiProductsIndexRoute: ApiProductsIndexRoute,
  ApiQuantityUnitsIndexRoute: ApiQuantityUnitsIndexRoute,
  ApiRecipesIndexRoute: ApiRecipesIndexRoute,
  ApiStockEntriesIndexRoute: ApiStockEntriesIndexRoute,
  ApiStockLogsIndexRoute: ApiStockLogsIndexRoute,
  ApiUnitConversionsIndexRoute: ApiUnitConversionsIndexRoute,
  ApiUploadsIndexRoute: ApiUploadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
