/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresIndexRouteImport } from './routes/stores/index'
import { Route as StockIndexRouteImport } from './routes/stock/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as RecipeCategoriesIndexRouteImport } from './routes/recipe-categories/index'
import { Route as QuantityUnitsIndexRouteImport } from './routes/quantity-units/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductCategoriesIndexRouteImport } from './routes/product-categories/index'
import { Route as MealPlanIndexRouteImport } from './routes/meal-plan/index'
import { Route as StoresIdRouteImport } from './routes/stores/$id'
import { Route as RecipesIdRouteImport } from './routes/recipes/$id'
import { Route as RecipeCategoriesIdRouteImport } from './routes/recipe-categories/$id'
import { Route as QuantityUnitsIdRouteImport } from './routes/quantity-units/$id'
import { Route as ProductsIdRouteImport } from './routes/products/$id'
import { Route as ProductCategoriesIdRouteImport } from './routes/product-categories/$id'
import { Route as MealPlanShoppingListRouteImport } from './routes/meal-plan/shopping-list'
import { Route as ApiWebhooksIndexRouteImport } from './routes/api/webhooks/index'
import { Route as ApiUploadsIndexRouteImport } from './routes/api/uploads/index'
import { Route as ApiUnitConversionsIndexRouteImport } from './routes/api/unit-conversions/index'
import { Route as ApiStoresIndexRouteImport } from './routes/api/stores/index'
import { Route as ApiStockLogsIndexRouteImport } from './routes/api/stock-logs/index'
import { Route as ApiStockEntriesIndexRouteImport } from './routes/api/stock-entries/index'
import { Route as ApiRecipesIndexRouteImport } from './routes/api/recipes/index'
import { Route as ApiRecipeCategoriesIndexRouteImport } from './routes/api/recipe-categories/index'
import { Route as ApiQuantityUnitsIndexRouteImport } from './routes/api/quantity-units/index'
import { Route as ApiProductsIndexRouteImport } from './routes/api/products/index'
import { Route as ApiProductCategoriesIndexRouteImport } from './routes/api/product-categories/index'
import { Route as ApiMealSlotsIndexRouteImport } from './routes/api/meal-slots/index'
import { Route as ApiMealPlanEntriesIndexRouteImport } from './routes/api/meal-plan-entries/index'
import { Route as ApiApiKeysIndexRouteImport } from './routes/api/api-keys/index'
import { Route as ApiWebhooksRetryRouteImport } from './routes/api/webhooks/retry'
import { Route as ApiWebhooksIdRouteImport } from './routes/api/webhooks/$id'
import { Route as ApiUploadsFilenameRouteImport } from './routes/api/uploads/$filename'
import { Route as ApiUnitConversionsIdRouteImport } from './routes/api/unit-conversions/$id'
import { Route as ApiStoresIdRouteImport } from './routes/api/stores/$id'
import { Route as ApiStockLogsIdRouteImport } from './routes/api/stock-logs/$id'
import { Route as ApiStockEntriesConsumeRouteImport } from './routes/api/stock-entries/consume'
import { Route as ApiStockEntriesIdRouteImport } from './routes/api/stock-entries/$id'
import { Route as ApiRecipesIdRouteImport } from './routes/api/recipes/$id'
import { Route as ApiRecipeCategoriesIdRouteImport } from './routes/api/recipe-categories/$id'
import { Route as ApiQuantityUnitsIdRouteImport } from './routes/api/quantity-units/$id'
import { Route as ApiProductsIdRouteImport } from './routes/api/products/$id'
import { Route as ApiProductCategoriesIdRouteImport } from './routes/api/product-categories/$id'
import { Route as ApiMealSlotsReorderRouteImport } from './routes/api/meal-slots/reorder'
import { Route as ApiMealSlotsIdRouteImport } from './routes/api/meal-slots/$id'
import { Route as ApiMealPlanEntriesIngredientSummaryRouteImport } from './routes/api/meal-plan-entries/ingredient-summary'
import { Route as ApiMealPlanEntriesCookRouteImport } from './routes/api/meal-plan-entries/cook'
import { Route as ApiMealPlanEntriesIdRouteImport } from './routes/api/meal-plan-entries/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiApiKeysIdRouteImport } from './routes/api/api-keys/$id'
import { Route as ApiRecipesIdIngredientsIndexRouteImport } from './routes/api/recipes/$id/ingredients/index'
import { Route as ApiProductsIdUnitConversionsIndexRouteImport } from './routes/api/products/$id/unit-conversions/index'
import { Route as ApiRecipesIdIngredientsIngredientIdRouteImport } from './routes/api/recipes/$id/ingredients/$ingredientId'
import { Route as ApiProductsIdUnitConversionsConversionIdRouteImport } from './routes/api/products/$id/unit-conversions/$conversionId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeCategoriesIndexRoute = RecipeCategoriesIndexRouteImport.update({
  id: '/recipe-categories/',
  path: '/recipe-categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantityUnitsIndexRoute = QuantityUnitsIndexRouteImport.update({
  id: '/quantity-units/',
  path: '/quantity-units/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCategoriesIndexRoute = ProductCategoriesIndexRouteImport.update({
  id: '/product-categories/',
  path: '/product-categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlanIndexRoute = MealPlanIndexRouteImport.update({
  id: '/meal-plan/',
  path: '/meal-plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIdRoute = StoresIdRouteImport.update({
  id: '/stores/$id',
  path: '/stores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeCategoriesIdRoute = RecipeCategoriesIdRouteImport.update({
  id: '/recipe-categories/$id',
  path: '/recipe-categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantityUnitsIdRoute = QuantityUnitsIdRouteImport.update({
  id: '/quantity-units/$id',
  path: '/quantity-units/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCategoriesIdRoute = ProductCategoriesIdRouteImport.update({
  id: '/product-categories/$id',
  path: '/product-categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlanShoppingListRoute = MealPlanShoppingListRouteImport.update({
  id: '/meal-plan/shopping-list',
  path: '/meal-plan/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksIndexRoute = ApiWebhooksIndexRouteImport.update({
  id: '/api/webhooks/',
  path: '/api/webhooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsIndexRoute = ApiUploadsIndexRouteImport.update({
  id: '/api/uploads/',
  path: '/api/uploads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnitConversionsIndexRoute = ApiUnitConversionsIndexRouteImport.update({
  id: '/api/unit-conversions/',
  path: '/api/unit-conversions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoresIndexRoute = ApiStoresIndexRouteImport.update({
  id: '/api/stores/',
  path: '/api/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStockLogsIndexRoute = ApiStockLogsIndexRouteImport.update({
  id: '/api/stock-logs/',
  path: '/api/stock-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStockEntriesIndexRoute = ApiStockEntriesIndexRouteImport.update({
  id: '/api/stock-entries/',
  path: '/api/stock-entries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesIndexRoute = ApiRecipesIndexRouteImport.update({
  id: '/api/recipes/',
  path: '/api/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipeCategoriesIndexRoute =
  ApiRecipeCategoriesIndexRouteImport.update({
    id: '/api/recipe-categories/',
    path: '/api/recipe-categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQuantityUnitsIndexRoute = ApiQuantityUnitsIndexRouteImport.update({
  id: '/api/quantity-units/',
  path: '/api/quantity-units/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIndexRoute = ApiProductsIndexRouteImport.update({
  id: '/api/products/',
  path: '/api/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductCategoriesIndexRoute =
  ApiProductCategoriesIndexRouteImport.update({
    id: '/api/product-categories/',
    path: '/api/product-categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMealSlotsIndexRoute = ApiMealSlotsIndexRouteImport.update({
  id: '/api/meal-slots/',
  path: '/api/meal-slots/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMealPlanEntriesIndexRoute = ApiMealPlanEntriesIndexRouteImport.update({
  id: '/api/meal-plan-entries/',
  path: '/api/meal-plan-entries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysIndexRoute = ApiApiKeysIndexRouteImport.update({
  id: '/api/api-keys/',
  path: '/api/api-keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRetryRoute = ApiWebhooksRetryRouteImport.update({
  id: '/api/webhooks/retry',
  path: '/api/webhooks/retry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksIdRoute = ApiWebhooksIdRouteImport.update({
  id: '/api/webhooks/$id',
  path: '/api/webhooks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsFilenameRoute = ApiUploadsFilenameRouteImport.update({
  id: '/api/uploads/$filename',
  path: '/api/uploads/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnitConversionsIdRoute = ApiUnitConversionsIdRouteImport.update({
  id: '/api/unit-conversions/$id',
  path: '/api/unit-conversions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoresIdRoute = ApiStoresIdRouteImport.update({
  id: '/api/stores/$id',
  path: '/api/stores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStockLogsIdRoute = ApiStockLogsIdRouteImport.update({
  id: '/api/stock-logs/$id',
  path: '/api/stock-logs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStockEntriesConsumeRoute = ApiStockEntriesConsumeRouteImport.update({
  id: '/api/stock-entries/consume',
  path: '/api/stock-entries/consume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStockEntriesIdRoute = ApiStockEntriesIdRouteImport.update({
  id: '/api/stock-entries/$id',
  path: '/api/stock-entries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesIdRoute = ApiRecipesIdRouteImport.update({
  id: '/api/recipes/$id',
  path: '/api/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipeCategoriesIdRoute = ApiRecipeCategoriesIdRouteImport.update({
  id: '/api/recipe-categories/$id',
  path: '/api/recipe-categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuantityUnitsIdRoute = ApiQuantityUnitsIdRouteImport.update({
  id: '/api/quantity-units/$id',
  path: '/api/quantity-units/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/api/products/$id',
  path: '/api/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductCategoriesIdRoute = ApiProductCategoriesIdRouteImport.update({
  id: '/api/product-categories/$id',
  path: '/api/product-categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMealSlotsReorderRoute = ApiMealSlotsReorderRouteImport.update({
  id: '/api/meal-slots/reorder',
  path: '/api/meal-slots/reorder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMealSlotsIdRoute = ApiMealSlotsIdRouteImport.update({
  id: '/api/meal-slots/$id',
  path: '/api/meal-slots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMealPlanEntriesIngredientSummaryRoute =
  ApiMealPlanEntriesIngredientSummaryRouteImport.update({
    id: '/api/meal-plan-entries/ingredient-summary',
    path: '/api/meal-plan-entries/ingredient-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMealPlanEntriesCookRoute = ApiMealPlanEntriesCookRouteImport.update({
  id: '/api/meal-plan-entries/cook',
  path: '/api/meal-plan-entries/cook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMealPlanEntriesIdRoute = ApiMealPlanEntriesIdRouteImport.update({
  id: '/api/meal-plan-entries/$id',
  path: '/api/meal-plan-entries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysIdRoute = ApiApiKeysIdRouteImport.update({
  id: '/api/api-keys/$id',
  path: '/api/api-keys/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesIdIngredientsIndexRoute =
  ApiRecipesIdIngredientsIndexRouteImport.update({
    id: '/ingredients/',
    path: '/ingredients/',
    getParentRoute: () => ApiRecipesIdRoute,
  } as any)
const ApiProductsIdUnitConversionsIndexRoute =
  ApiProductsIdUnitConversionsIndexRouteImport.update({
    id: '/unit-conversions/',
    path: '/unit-conversions/',
    getParentRoute: () => ApiProductsIdRoute,
  } as any)
const ApiRecipesIdIngredientsIngredientIdRoute =
  ApiRecipesIdIngredientsIngredientIdRouteImport.update({
    id: '/ingredients/$ingredientId',
    path: '/ingredients/$ingredientId',
    getParentRoute: () => ApiRecipesIdRoute,
  } as any)
const ApiProductsIdUnitConversionsConversionIdRoute =
  ApiProductsIdUnitConversionsConversionIdRouteImport.update({
    id: '/unit-conversions/$conversionId',
    path: '/unit-conversions/$conversionId',
    getParentRoute: () => ApiProductsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/meal-plan/shopping-list': typeof MealPlanShoppingListRoute
  '/product-categories/$id': typeof ProductCategoriesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/quantity-units/$id': typeof QuantityUnitsIdRoute
  '/recipe-categories/$id': typeof RecipeCategoriesIdRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/meal-plan/': typeof MealPlanIndexRoute
  '/product-categories/': typeof ProductCategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/quantity-units/': typeof QuantityUnitsIndexRoute
  '/recipe-categories/': typeof RecipeCategoriesIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/stock/': typeof StockIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/api/api-keys/$id': typeof ApiApiKeysIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/meal-plan-entries/$id': typeof ApiMealPlanEntriesIdRoute
  '/api/meal-plan-entries/cook': typeof ApiMealPlanEntriesCookRoute
  '/api/meal-plan-entries/ingredient-summary': typeof ApiMealPlanEntriesIngredientSummaryRoute
  '/api/meal-slots/$id': typeof ApiMealSlotsIdRoute
  '/api/meal-slots/reorder': typeof ApiMealSlotsReorderRoute
  '/api/product-categories/$id': typeof ApiProductCategoriesIdRoute
  '/api/products/$id': typeof ApiProductsIdRouteWithChildren
  '/api/quantity-units/$id': typeof ApiQuantityUnitsIdRoute
  '/api/recipe-categories/$id': typeof ApiRecipeCategoriesIdRoute
  '/api/recipes/$id': typeof ApiRecipesIdRouteWithChildren
  '/api/stock-entries/$id': typeof ApiStockEntriesIdRoute
  '/api/stock-entries/consume': typeof ApiStockEntriesConsumeRoute
  '/api/stock-logs/$id': typeof ApiStockLogsIdRoute
  '/api/stores/$id': typeof ApiStoresIdRoute
  '/api/unit-conversions/$id': typeof ApiUnitConversionsIdRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/api/webhooks/$id': typeof ApiWebhooksIdRoute
  '/api/webhooks/retry': typeof ApiWebhooksRetryRoute
  '/api/api-keys/': typeof ApiApiKeysIndexRoute
  '/api/meal-plan-entries/': typeof ApiMealPlanEntriesIndexRoute
  '/api/meal-slots/': typeof ApiMealSlotsIndexRoute
  '/api/product-categories/': typeof ApiProductCategoriesIndexRoute
  '/api/products/': typeof ApiProductsIndexRoute
  '/api/quantity-units/': typeof ApiQuantityUnitsIndexRoute
  '/api/recipe-categories/': typeof ApiRecipeCategoriesIndexRoute
  '/api/recipes/': typeof ApiRecipesIndexRoute
  '/api/stock-entries/': typeof ApiStockEntriesIndexRoute
  '/api/stock-logs/': typeof ApiStockLogsIndexRoute
  '/api/stores/': typeof ApiStoresIndexRoute
  '/api/unit-conversions/': typeof ApiUnitConversionsIndexRoute
  '/api/uploads/': typeof ApiUploadsIndexRoute
  '/api/webhooks/': typeof ApiWebhooksIndexRoute
  '/api/products/$id/unit-conversions/$conversionId': typeof ApiProductsIdUnitConversionsConversionIdRoute
  '/api/recipes/$id/ingredients/$ingredientId': typeof ApiRecipesIdIngredientsIngredientIdRoute
  '/api/products/$id/unit-conversions/': typeof ApiProductsIdUnitConversionsIndexRoute
  '/api/recipes/$id/ingredients/': typeof ApiRecipesIdIngredientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/meal-plan/shopping-list': typeof MealPlanShoppingListRoute
  '/product-categories/$id': typeof ProductCategoriesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/quantity-units/$id': typeof QuantityUnitsIdRoute
  '/recipe-categories/$id': typeof RecipeCategoriesIdRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/meal-plan': typeof MealPlanIndexRoute
  '/product-categories': typeof ProductCategoriesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/quantity-units': typeof QuantityUnitsIndexRoute
  '/recipe-categories': typeof RecipeCategoriesIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/stock': typeof StockIndexRoute
  '/stores': typeof StoresIndexRoute
  '/api/api-keys/$id': typeof ApiApiKeysIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/meal-plan-entries/$id': typeof ApiMealPlanEntriesIdRoute
  '/api/meal-plan-entries/cook': typeof ApiMealPlanEntriesCookRoute
  '/api/meal-plan-entries/ingredient-summary': typeof ApiMealPlanEntriesIngredientSummaryRoute
  '/api/meal-slots/$id': typeof ApiMealSlotsIdRoute
  '/api/meal-slots/reorder': typeof ApiMealSlotsReorderRoute
  '/api/product-categories/$id': typeof ApiProductCategoriesIdRoute
  '/api/products/$id': typeof ApiProductsIdRouteWithChildren
  '/api/quantity-units/$id': typeof ApiQuantityUnitsIdRoute
  '/api/recipe-categories/$id': typeof ApiRecipeCategoriesIdRoute
  '/api/recipes/$id': typeof ApiRecipesIdRouteWithChildren
  '/api/stock-entries/$id': typeof ApiStockEntriesIdRoute
  '/api/stock-entries/consume': typeof ApiStockEntriesConsumeRoute
  '/api/stock-logs/$id': typeof ApiStockLogsIdRoute
  '/api/stores/$id': typeof ApiStoresIdRoute
  '/api/unit-conversions/$id': typeof ApiUnitConversionsIdRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/api/webhooks/$id': typeof ApiWebhooksIdRoute
  '/api/webhooks/retry': typeof ApiWebhooksRetryRoute
  '/api/api-keys': typeof ApiApiKeysIndexRoute
  '/api/meal-plan-entries': typeof ApiMealPlanEntriesIndexRoute
  '/api/meal-slots': typeof ApiMealSlotsIndexRoute
  '/api/product-categories': typeof ApiProductCategoriesIndexRoute
  '/api/products': typeof ApiProductsIndexRoute
  '/api/quantity-units': typeof ApiQuantityUnitsIndexRoute
  '/api/recipe-categories': typeof ApiRecipeCategoriesIndexRoute
  '/api/recipes': typeof ApiRecipesIndexRoute
  '/api/stock-entries': typeof ApiStockEntriesIndexRoute
  '/api/stock-logs': typeof ApiStockLogsIndexRoute
  '/api/stores': typeof ApiStoresIndexRoute
  '/api/unit-conversions': typeof ApiUnitConversionsIndexRoute
  '/api/uploads': typeof ApiUploadsIndexRoute
  '/api/webhooks': typeof ApiWebhooksIndexRoute
  '/api/products/$id/unit-conversions/$conversionId': typeof ApiProductsIdUnitConversionsConversionIdRoute
  '/api/recipes/$id/ingredients/$ingredientId': typeof ApiRecipesIdIngredientsIngredientIdRoute
  '/api/products/$id/unit-conversions': typeof ApiProductsIdUnitConversionsIndexRoute
  '/api/recipes/$id/ingredients': typeof ApiRecipesIdIngredientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/meal-plan/shopping-list': typeof MealPlanShoppingListRoute
  '/product-categories/$id': typeof ProductCategoriesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/quantity-units/$id': typeof QuantityUnitsIdRoute
  '/recipe-categories/$id': typeof RecipeCategoriesIdRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/meal-plan/': typeof MealPlanIndexRoute
  '/product-categories/': typeof ProductCategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/quantity-units/': typeof QuantityUnitsIndexRoute
  '/recipe-categories/': typeof RecipeCategoriesIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/stock/': typeof StockIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/api/api-keys/$id': typeof ApiApiKeysIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/meal-plan-entries/$id': typeof ApiMealPlanEntriesIdRoute
  '/api/meal-plan-entries/cook': typeof ApiMealPlanEntriesCookRoute
  '/api/meal-plan-entries/ingredient-summary': typeof ApiMealPlanEntriesIngredientSummaryRoute
  '/api/meal-slots/$id': typeof ApiMealSlotsIdRoute
  '/api/meal-slots/reorder': typeof ApiMealSlotsReorderRoute
  '/api/product-categories/$id': typeof ApiProductCategoriesIdRoute
  '/api/products/$id': typeof ApiProductsIdRouteWithChildren
  '/api/quantity-units/$id': typeof ApiQuantityUnitsIdRoute
  '/api/recipe-categories/$id': typeof ApiRecipeCategoriesIdRoute
  '/api/recipes/$id': typeof ApiRecipesIdRouteWithChildren
  '/api/stock-entries/$id': typeof ApiStockEntriesIdRoute
  '/api/stock-entries/consume': typeof ApiStockEntriesConsumeRoute
  '/api/stock-logs/$id': typeof ApiStockLogsIdRoute
  '/api/stores/$id': typeof ApiStoresIdRoute
  '/api/unit-conversions/$id': typeof ApiUnitConversionsIdRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/api/webhooks/$id': typeof ApiWebhooksIdRoute
  '/api/webhooks/retry': typeof ApiWebhooksRetryRoute
  '/api/api-keys/': typeof ApiApiKeysIndexRoute
  '/api/meal-plan-entries/': typeof ApiMealPlanEntriesIndexRoute
  '/api/meal-slots/': typeof ApiMealSlotsIndexRoute
  '/api/product-categories/': typeof ApiProductCategoriesIndexRoute
  '/api/products/': typeof ApiProductsIndexRoute
  '/api/quantity-units/': typeof ApiQuantityUnitsIndexRoute
  '/api/recipe-categories/': typeof ApiRecipeCategoriesIndexRoute
  '/api/recipes/': typeof ApiRecipesIndexRoute
  '/api/stock-entries/': typeof ApiStockEntriesIndexRoute
  '/api/stock-logs/': typeof ApiStockLogsIndexRoute
  '/api/stores/': typeof ApiStoresIndexRoute
  '/api/unit-conversions/': typeof ApiUnitConversionsIndexRoute
  '/api/uploads/': typeof ApiUploadsIndexRoute
  '/api/webhooks/': typeof ApiWebhooksIndexRoute
  '/api/products/$id/unit-conversions/$conversionId': typeof ApiProductsIdUnitConversionsConversionIdRoute
  '/api/recipes/$id/ingredients/$ingredientId': typeof ApiRecipesIdIngredientsIngredientIdRoute
  '/api/products/$id/unit-conversions/': typeof ApiProductsIdUnitConversionsIndexRoute
  '/api/recipes/$id/ingredients/': typeof ApiRecipesIdIngredientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/profile'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/meal-plan/shopping-list'
    | '/product-categories/$id'
    | '/products/$id'
    | '/quantity-units/$id'
    | '/recipe-categories/$id'
    | '/recipes/$id'
    | '/stores/$id'
    | '/meal-plan/'
    | '/product-categories/'
    | '/products/'
    | '/quantity-units/'
    | '/recipe-categories/'
    | '/recipes/'
    | '/stock/'
    | '/stores/'
    | '/api/api-keys/$id'
    | '/api/auth/$'
    | '/api/meal-plan-entries/$id'
    | '/api/meal-plan-entries/cook'
    | '/api/meal-plan-entries/ingredient-summary'
    | '/api/meal-slots/$id'
    | '/api/meal-slots/reorder'
    | '/api/product-categories/$id'
    | '/api/products/$id'
    | '/api/quantity-units/$id'
    | '/api/recipe-categories/$id'
    | '/api/recipes/$id'
    | '/api/stock-entries/$id'
    | '/api/stock-entries/consume'
    | '/api/stock-logs/$id'
    | '/api/stores/$id'
    | '/api/unit-conversions/$id'
    | '/api/uploads/$filename'
    | '/api/webhooks/$id'
    | '/api/webhooks/retry'
    | '/api/api-keys/'
    | '/api/meal-plan-entries/'
    | '/api/meal-slots/'
    | '/api/product-categories/'
    | '/api/products/'
    | '/api/quantity-units/'
    | '/api/recipe-categories/'
    | '/api/recipes/'
    | '/api/stock-entries/'
    | '/api/stock-logs/'
    | '/api/stores/'
    | '/api/unit-conversions/'
    | '/api/uploads/'
    | '/api/webhooks/'
    | '/api/products/$id/unit-conversions/$conversionId'
    | '/api/recipes/$id/ingredients/$ingredientId'
    | '/api/products/$id/unit-conversions/'
    | '/api/recipes/$id/ingredients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/profile'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/meal-plan/shopping-list'
    | '/product-categories/$id'
    | '/products/$id'
    | '/quantity-units/$id'
    | '/recipe-categories/$id'
    | '/recipes/$id'
    | '/stores/$id'
    | '/meal-plan'
    | '/product-categories'
    | '/products'
    | '/quantity-units'
    | '/recipe-categories'
    | '/recipes'
    | '/stock'
    | '/stores'
    | '/api/api-keys/$id'
    | '/api/auth/$'
    | '/api/meal-plan-entries/$id'
    | '/api/meal-plan-entries/cook'
    | '/api/meal-plan-entries/ingredient-summary'
    | '/api/meal-slots/$id'
    | '/api/meal-slots/reorder'
    | '/api/product-categories/$id'
    | '/api/products/$id'
    | '/api/quantity-units/$id'
    | '/api/recipe-categories/$id'
    | '/api/recipes/$id'
    | '/api/stock-entries/$id'
    | '/api/stock-entries/consume'
    | '/api/stock-logs/$id'
    | '/api/stores/$id'
    | '/api/unit-conversions/$id'
    | '/api/uploads/$filename'
    | '/api/webhooks/$id'
    | '/api/webhooks/retry'
    | '/api/api-keys'
    | '/api/meal-plan-entries'
    | '/api/meal-slots'
    | '/api/product-categories'
    | '/api/products'
    | '/api/quantity-units'
    | '/api/recipe-categories'
    | '/api/recipes'
    | '/api/stock-entries'
    | '/api/stock-logs'
    | '/api/stores'
    | '/api/unit-conversions'
    | '/api/uploads'
    | '/api/webhooks'
    | '/api/products/$id/unit-conversions/$conversionId'
    | '/api/recipes/$id/ingredients/$ingredientId'
    | '/api/products/$id/unit-conversions'
    | '/api/recipes/$id/ingredients'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/forgot-password'
    | '/profile'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/meal-plan/shopping-list'
    | '/product-categories/$id'
    | '/products/$id'
    | '/quantity-units/$id'
    | '/recipe-categories/$id'
    | '/recipes/$id'
    | '/stores/$id'
    | '/meal-plan/'
    | '/product-categories/'
    | '/products/'
    | '/quantity-units/'
    | '/recipe-categories/'
    | '/recipes/'
    | '/stock/'
    | '/stores/'
    | '/api/api-keys/$id'
    | '/api/auth/$'
    | '/api/meal-plan-entries/$id'
    | '/api/meal-plan-entries/cook'
    | '/api/meal-plan-entries/ingredient-summary'
    | '/api/meal-slots/$id'
    | '/api/meal-slots/reorder'
    | '/api/product-categories/$id'
    | '/api/products/$id'
    | '/api/quantity-units/$id'
    | '/api/recipe-categories/$id'
    | '/api/recipes/$id'
    | '/api/stock-entries/$id'
    | '/api/stock-entries/consume'
    | '/api/stock-logs/$id'
    | '/api/stores/$id'
    | '/api/unit-conversions/$id'
    | '/api/uploads/$filename'
    | '/api/webhooks/$id'
    | '/api/webhooks/retry'
    | '/api/api-keys/'
    | '/api/meal-plan-entries/'
    | '/api/meal-slots/'
    | '/api/product-categories/'
    | '/api/products/'
    | '/api/quantity-units/'
    | '/api/recipe-categories/'
    | '/api/recipes/'
    | '/api/stock-entries/'
    | '/api/stock-logs/'
    | '/api/stores/'
    | '/api/unit-conversions/'
    | '/api/uploads/'
    | '/api/webhooks/'
    | '/api/products/$id/unit-conversions/$conversionId'
    | '/api/recipes/$id/ingredients/$ingredientId'
    | '/api/products/$id/unit-conversions/'
    | '/api/recipes/$id/ingredients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  MealPlanShoppingListRoute: typeof MealPlanShoppingListRoute
  ProductCategoriesIdRoute: typeof ProductCategoriesIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  QuantityUnitsIdRoute: typeof QuantityUnitsIdRoute
  RecipeCategoriesIdRoute: typeof RecipeCategoriesIdRoute
  RecipesIdRoute: typeof RecipesIdRoute
  StoresIdRoute: typeof StoresIdRoute
  MealPlanIndexRoute: typeof MealPlanIndexRoute
  ProductCategoriesIndexRoute: typeof ProductCategoriesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  QuantityUnitsIndexRoute: typeof QuantityUnitsIndexRoute
  RecipeCategoriesIndexRoute: typeof RecipeCategoriesIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  StockIndexRoute: typeof StockIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
  ApiApiKeysIdRoute: typeof ApiApiKeysIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMealPlanEntriesIdRoute: typeof ApiMealPlanEntriesIdRoute
  ApiMealPlanEntriesCookRoute: typeof ApiMealPlanEntriesCookRoute
  ApiMealPlanEntriesIngredientSummaryRoute: typeof ApiMealPlanEntriesIngredientSummaryRoute
  ApiMealSlotsIdRoute: typeof ApiMealSlotsIdRoute
  ApiMealSlotsReorderRoute: typeof ApiMealSlotsReorderRoute
  ApiProductCategoriesIdRoute: typeof ApiProductCategoriesIdRoute
  ApiProductsIdRoute: typeof ApiProductsIdRouteWithChildren
  ApiQuantityUnitsIdRoute: typeof ApiQuantityUnitsIdRoute
  ApiRecipeCategoriesIdRoute: typeof ApiRecipeCategoriesIdRoute
  ApiRecipesIdRoute: typeof ApiRecipesIdRouteWithChildren
  ApiStockEntriesIdRoute: typeof ApiStockEntriesIdRoute
  ApiStockEntriesConsumeRoute: typeof ApiStockEntriesConsumeRoute
  ApiStockLogsIdRoute: typeof ApiStockLogsIdRoute
  ApiStoresIdRoute: typeof ApiStoresIdRoute
  ApiUnitConversionsIdRoute: typeof ApiUnitConversionsIdRoute
  ApiUploadsFilenameRoute: typeof ApiUploadsFilenameRoute
  ApiWebhooksIdRoute: typeof ApiWebhooksIdRoute
  ApiWebhooksRetryRoute: typeof ApiWebhooksRetryRoute
  ApiApiKeysIndexRoute: typeof ApiApiKeysIndexRoute
  ApiMealPlanEntriesIndexRoute: typeof ApiMealPlanEntriesIndexRoute
  ApiMealSlotsIndexRoute: typeof ApiMealSlotsIndexRoute
  ApiProductCategoriesIndexRoute: typeof ApiProductCategoriesIndexRoute
  ApiProductsIndexRoute: typeof ApiProductsIndexRoute
  ApiQuantityUnitsIndexRoute: typeof ApiQuantityUnitsIndexRoute
  ApiRecipeCategoriesIndexRoute: typeof ApiRecipeCategoriesIndexRoute
  ApiRecipesIndexRoute: typeof ApiRecipesIndexRoute
  ApiStockEntriesIndexRoute: typeof ApiStockEntriesIndexRoute
  ApiStockLogsIndexRoute: typeof ApiStockLogsIndexRoute
  ApiStoresIndexRoute: typeof ApiStoresIndexRoute
  ApiUnitConversionsIndexRoute: typeof ApiUnitConversionsIndexRoute
  ApiUploadsIndexRoute: typeof ApiUploadsIndexRoute
  ApiWebhooksIndexRoute: typeof ApiWebhooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/': {
      id: '/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe-categories/': {
      id: '/recipe-categories/'
      path: '/recipe-categories'
      fullPath: '/recipe-categories/'
      preLoaderRoute: typeof RecipeCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantity-units/': {
      id: '/quantity-units/'
      path: '/quantity-units'
      fullPath: '/quantity-units/'
      preLoaderRoute: typeof QuantityUnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-categories/': {
      id: '/product-categories/'
      path: '/product-categories'
      fullPath: '/product-categories/'
      preLoaderRoute: typeof ProductCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plan/': {
      id: '/meal-plan/'
      path: '/meal-plan'
      fullPath: '/meal-plan/'
      preLoaderRoute: typeof MealPlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$id': {
      id: '/stores/$id'
      path: '/stores/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof StoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe-categories/$id': {
      id: '/recipe-categories/$id'
      path: '/recipe-categories/$id'
      fullPath: '/recipe-categories/$id'
      preLoaderRoute: typeof RecipeCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantity-units/$id': {
      id: '/quantity-units/$id'
      path: '/quantity-units/$id'
      fullPath: '/quantity-units/$id'
      preLoaderRoute: typeof QuantityUnitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-categories/$id': {
      id: '/product-categories/$id'
      path: '/product-categories/$id'
      fullPath: '/product-categories/$id'
      preLoaderRoute: typeof ProductCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plan/shopping-list': {
      id: '/meal-plan/shopping-list'
      path: '/meal-plan/shopping-list'
      fullPath: '/meal-plan/shopping-list'
      preLoaderRoute: typeof MealPlanShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/': {
      id: '/api/webhooks/'
      path: '/api/webhooks'
      fullPath: '/api/webhooks/'
      preLoaderRoute: typeof ApiWebhooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/': {
      id: '/api/uploads/'
      path: '/api/uploads'
      fullPath: '/api/uploads/'
      preLoaderRoute: typeof ApiUploadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unit-conversions/': {
      id: '/api/unit-conversions/'
      path: '/api/unit-conversions'
      fullPath: '/api/unit-conversions/'
      preLoaderRoute: typeof ApiUnitConversionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stores/': {
      id: '/api/stores/'
      path: '/api/stores'
      fullPath: '/api/stores/'
      preLoaderRoute: typeof ApiStoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stock-logs/': {
      id: '/api/stock-logs/'
      path: '/api/stock-logs'
      fullPath: '/api/stock-logs/'
      preLoaderRoute: typeof ApiStockLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stock-entries/': {
      id: '/api/stock-entries/'
      path: '/api/stock-entries'
      fullPath: '/api/stock-entries/'
      preLoaderRoute: typeof ApiStockEntriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/': {
      id: '/api/recipes/'
      path: '/api/recipes'
      fullPath: '/api/recipes/'
      preLoaderRoute: typeof ApiRecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipe-categories/': {
      id: '/api/recipe-categories/'
      path: '/api/recipe-categories'
      fullPath: '/api/recipe-categories/'
      preLoaderRoute: typeof ApiRecipeCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quantity-units/': {
      id: '/api/quantity-units/'
      path: '/api/quantity-units'
      fullPath: '/api/quantity-units/'
      preLoaderRoute: typeof ApiQuantityUnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/': {
      id: '/api/products/'
      path: '/api/products'
      fullPath: '/api/products/'
      preLoaderRoute: typeof ApiProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/product-categories/': {
      id: '/api/product-categories/'
      path: '/api/product-categories'
      fullPath: '/api/product-categories/'
      preLoaderRoute: typeof ApiProductCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meal-slots/': {
      id: '/api/meal-slots/'
      path: '/api/meal-slots'
      fullPath: '/api/meal-slots/'
      preLoaderRoute: typeof ApiMealSlotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meal-plan-entries/': {
      id: '/api/meal-plan-entries/'
      path: '/api/meal-plan-entries'
      fullPath: '/api/meal-plan-entries/'
      preLoaderRoute: typeof ApiMealPlanEntriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys/': {
      id: '/api/api-keys/'
      path: '/api/api-keys'
      fullPath: '/api/api-keys/'
      preLoaderRoute: typeof ApiApiKeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/retry': {
      id: '/api/webhooks/retry'
      path: '/api/webhooks/retry'
      fullPath: '/api/webhooks/retry'
      preLoaderRoute: typeof ApiWebhooksRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/$id': {
      id: '/api/webhooks/$id'
      path: '/api/webhooks/$id'
      fullPath: '/api/webhooks/$id'
      preLoaderRoute: typeof ApiWebhooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$filename': {
      id: '/api/uploads/$filename'
      path: '/api/uploads/$filename'
      fullPath: '/api/uploads/$filename'
      preLoaderRoute: typeof ApiUploadsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unit-conversions/$id': {
      id: '/api/unit-conversions/$id'
      path: '/api/unit-conversions/$id'
      fullPath: '/api/unit-conversions/$id'
      preLoaderRoute: typeof ApiUnitConversionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stores/$id': {
      id: '/api/stores/$id'
      path: '/api/stores/$id'
      fullPath: '/api/stores/$id'
      preLoaderRoute: typeof ApiStoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stock-logs/$id': {
      id: '/api/stock-logs/$id'
      path: '/api/stock-logs/$id'
      fullPath: '/api/stock-logs/$id'
      preLoaderRoute: typeof ApiStockLogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stock-entries/consume': {
      id: '/api/stock-entries/consume'
      path: '/api/stock-entries/consume'
      fullPath: '/api/stock-entries/consume'
      preLoaderRoute: typeof ApiStockEntriesConsumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stock-entries/$id': {
      id: '/api/stock-entries/$id'
      path: '/api/stock-entries/$id'
      fullPath: '/api/stock-entries/$id'
      preLoaderRoute: typeof ApiStockEntriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/$id': {
      id: '/api/recipes/$id'
      path: '/api/recipes/$id'
      fullPath: '/api/recipes/$id'
      preLoaderRoute: typeof ApiRecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipe-categories/$id': {
      id: '/api/recipe-categories/$id'
      path: '/api/recipe-categories/$id'
      fullPath: '/api/recipe-categories/$id'
      preLoaderRoute: typeof ApiRecipeCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quantity-units/$id': {
      id: '/api/quantity-units/$id'
      path: '/api/quantity-units/$id'
      fullPath: '/api/quantity-units/$id'
      preLoaderRoute: typeof ApiQuantityUnitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/api/products/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/product-categories/$id': {
      id: '/api/product-categories/$id'
      path: '/api/product-categories/$id'
      fullPath: '/api/product-categories/$id'
      preLoaderRoute: typeof ApiProductCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meal-slots/reorder': {
      id: '/api/meal-slots/reorder'
      path: '/api/meal-slots/reorder'
      fullPath: '/api/meal-slots/reorder'
      preLoaderRoute: typeof ApiMealSlotsReorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meal-slots/$id': {
      id: '/api/meal-slots/$id'
      path: '/api/meal-slots/$id'
      fullPath: '/api/meal-slots/$id'
      preLoaderRoute: typeof ApiMealSlotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meal-plan-entries/ingredient-summary': {
      id: '/api/meal-plan-entries/ingredient-summary'
      path: '/api/meal-plan-entries/ingredient-summary'
      fullPath: '/api/meal-plan-entries/ingredient-summary'
      preLoaderRoute: typeof ApiMealPlanEntriesIngredientSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meal-plan-entries/cook': {
      id: '/api/meal-plan-entries/cook'
      path: '/api/meal-plan-entries/cook'
      fullPath: '/api/meal-plan-entries/cook'
      preLoaderRoute: typeof ApiMealPlanEntriesCookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meal-plan-entries/$id': {
      id: '/api/meal-plan-entries/$id'
      path: '/api/meal-plan-entries/$id'
      fullPath: '/api/meal-plan-entries/$id'
      preLoaderRoute: typeof ApiMealPlanEntriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys/$id': {
      id: '/api/api-keys/$id'
      path: '/api/api-keys/$id'
      fullPath: '/api/api-keys/$id'
      preLoaderRoute: typeof ApiApiKeysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/$id/ingredients/': {
      id: '/api/recipes/$id/ingredients/'
      path: '/ingredients'
      fullPath: '/api/recipes/$id/ingredients/'
      preLoaderRoute: typeof ApiRecipesIdIngredientsIndexRouteImport
      parentRoute: typeof ApiRecipesIdRoute
    }
    '/api/products/$id/unit-conversions/': {
      id: '/api/products/$id/unit-conversions/'
      path: '/unit-conversions'
      fullPath: '/api/products/$id/unit-conversions/'
      preLoaderRoute: typeof ApiProductsIdUnitConversionsIndexRouteImport
      parentRoute: typeof ApiProductsIdRoute
    }
    '/api/recipes/$id/ingredients/$ingredientId': {
      id: '/api/recipes/$id/ingredients/$ingredientId'
      path: '/ingredients/$ingredientId'
      fullPath: '/api/recipes/$id/ingredients/$ingredientId'
      preLoaderRoute: typeof ApiRecipesIdIngredientsIngredientIdRouteImport
      parentRoute: typeof ApiRecipesIdRoute
    }
    '/api/products/$id/unit-conversions/$conversionId': {
      id: '/api/products/$id/unit-conversions/$conversionId'
      path: '/unit-conversions/$conversionId'
      fullPath: '/api/products/$id/unit-conversions/$conversionId'
      preLoaderRoute: typeof ApiProductsIdUnitConversionsConversionIdRouteImport
      parentRoute: typeof ApiProductsIdRoute
    }
  }
}

interface ApiProductsIdRouteChildren {
  ApiProductsIdUnitConversionsConversionIdRoute: typeof ApiProductsIdUnitConversionsConversionIdRoute
  ApiProductsIdUnitConversionsIndexRoute: typeof ApiProductsIdUnitConversionsIndexRoute
}

const ApiProductsIdRouteChildren: ApiProductsIdRouteChildren = {
  ApiProductsIdUnitConversionsConversionIdRoute:
    ApiProductsIdUnitConversionsConversionIdRoute,
  ApiProductsIdUnitConversionsIndexRoute:
    ApiProductsIdUnitConversionsIndexRoute,
}

const ApiProductsIdRouteWithChildren = ApiProductsIdRoute._addFileChildren(
  ApiProductsIdRouteChildren,
)

interface ApiRecipesIdRouteChildren {
  ApiRecipesIdIngredientsIngredientIdRoute: typeof ApiRecipesIdIngredientsIngredientIdRoute
  ApiRecipesIdIngredientsIndexRoute: typeof ApiRecipesIdIngredientsIndexRoute
}

const ApiRecipesIdRouteChildren: ApiRecipesIdRouteChildren = {
  ApiRecipesIdIngredientsIngredientIdRoute:
    ApiRecipesIdIngredientsIngredientIdRoute,
  ApiRecipesIdIngredientsIndexRoute: ApiRecipesIdIngredientsIndexRoute,
}

const ApiRecipesIdRouteWithChildren = ApiRecipesIdRoute._addFileChildren(
  ApiRecipesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  MealPlanShoppingListRoute: MealPlanShoppingListRoute,
  ProductCategoriesIdRoute: ProductCategoriesIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  QuantityUnitsIdRoute: QuantityUnitsIdRoute,
  RecipeCategoriesIdRoute: RecipeCategoriesIdRoute,
  RecipesIdRoute: RecipesIdRoute,
  StoresIdRoute: StoresIdRoute,
  MealPlanIndexRoute: MealPlanIndexRoute,
  ProductCategoriesIndexRoute: ProductCategoriesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  QuantityUnitsIndexRoute: QuantityUnitsIndexRoute,
  RecipeCategoriesIndexRoute: RecipeCategoriesIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  StockIndexRoute: StockIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
  ApiApiKeysIdRoute: ApiApiKeysIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMealPlanEntriesIdRoute: ApiMealPlanEntriesIdRoute,
  ApiMealPlanEntriesCookRoute: ApiMealPlanEntriesCookRoute,
  ApiMealPlanEntriesIngredientSummaryRoute:
    ApiMealPlanEntriesIngredientSummaryRoute,
  ApiMealSlotsIdRoute: ApiMealSlotsIdRoute,
  ApiMealSlotsReorderRoute: ApiMealSlotsReorderRoute,
  ApiProductCategoriesIdRoute: ApiProductCategoriesIdRoute,
  ApiProductsIdRoute: ApiProductsIdRouteWithChildren,
  ApiQuantityUnitsIdRoute: ApiQuantityUnitsIdRoute,
  ApiRecipeCategoriesIdRoute: ApiRecipeCategoriesIdRoute,
  ApiRecipesIdRoute: ApiRecipesIdRouteWithChildren,
  ApiStockEntriesIdRoute: ApiStockEntriesIdRoute,
  ApiStockEntriesConsumeRoute: ApiStockEntriesConsumeRoute,
  ApiStockLogsIdRoute: ApiStockLogsIdRoute,
  ApiStoresIdRoute: ApiStoresIdRoute,
  ApiUnitConversionsIdRoute: ApiUnitConversionsIdRoute,
  ApiUploadsFilenameRoute: ApiUploadsFilenameRoute,
  ApiWebhooksIdRoute: ApiWebhooksIdRoute,
  ApiWebhooksRetryRoute: ApiWebhooksRetryRoute,
  ApiApiKeysIndexRoute: ApiApiKeysIndexRoute,
  ApiMealPlanEntriesIndexRoute: ApiMealPlanEntriesIndexRoute,
  ApiMealSlotsIndexRoute: ApiMealSlotsIndexRoute,
  ApiProductCategoriesIndexRoute: ApiProductCategoriesIndexRoute,
  ApiProductsIndexRoute: ApiProductsIndexRoute,
  ApiQuantityUnitsIndexRoute: ApiQuantityUnitsIndexRoute,
  ApiRecipeCategoriesIndexRoute: ApiRecipeCategoriesIndexRoute,
  ApiRecipesIndexRoute: ApiRecipesIndexRoute,
  ApiStockEntriesIndexRoute: ApiStockEntriesIndexRoute,
  ApiStockLogsIndexRoute: ApiStockLogsIndexRoute,
  ApiStoresIndexRoute: ApiStoresIndexRoute,
  ApiUnitConversionsIndexRoute: ApiUnitConversionsIndexRoute,
  ApiUploadsIndexRoute: ApiUploadsIndexRoute,
  ApiWebhooksIndexRoute: ApiWebhooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
